[pytest]
python_files = test_*.py

python_classes = Test*

python_functions = test_*


markers = 
    ui: маркировка для юай тестов
    slow:маркировка для медленных тестов
    smoke: маркировка для дымовых тестов
    critical: маркировка для кричитчных тестов
    regression: маркировка регрессионных тестов
    registration: маркировка регистрации пользователей
    aythorization: маркировка для тестов, связанных с авторизацией
